# Generated by Django 3.0.6 on 2020-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_model',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_model',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남자'), ('W', '여자'), ('O', '그 밖의 성')], max_length=10, null=True),
        ),
    ]
