# Generated by Django 3.0.6 on 2020-08-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_m',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
